image: registry.forge.orange-labs.fr/org.eclipse.om2m/om2m/com.orange.om2m.docker.builder:0.0.2

stages:
  - build
  - test
  - deploy


build:
  stage: build
  script: "mvn clean install -B"
  tags:
    - docker
    - forge
    - shared
    
deploy:
  stage: deploy
  script: "mvn deploy -B -DaltDeploymentRepository=inhouse.snapshot::default::http://maven2.rd.francetelecom.fr/proxy/repository/inhouse.snapshot"
  tags:
    - docker
    - innovation
    - shared
