before_script:
  - export HTTP_PROXY="proxy.rd.francetelecom.fr:3128"
  - export HTTPS_PROXY="proxy.rd.francetelecom.fr:3128"
  - export http_proxy="proxy.rd.francetelecom.fr:3128"

image: registry.forge.orange-labs.fr/org.eclipse.om2m/om2m/com.orange.om2m.docker.builder:0.0.1

build:
  script: "mvn clean install -B"
  variables: 
    HTTP_PROXY: "proxy.rd.francetelecom.fr:3128"
    HTTPS_PROXY: "proxy.rd.francetelecom.fr:3128"
  tags:
    - docker
    - forge
    - shared
