before_script:
  - export HTTP_PROXY="proxy.rd.francetelecom.fr:3128"
  - export HTTPS_PROXY="proxy.rd.francetelecom.fr:3128"
  - export http_proxy="proxy.rd.francetelecom.fr:3128"

image: registry.forge.orange-labs.fr/mpcy8647/org.eclipse.om2m:0.0.2

build:
  script: "mvn clean install -B"
  tags:
    - docker
    - forge
    - shared
